<script>
window.SILAKU_FAQ_DATA = {
    id: [
        {
            id: 'greeting',
            category: 'general',
            questions: ['Halo', 'Hai', 'Selamat pagi', 'Selamat siang', 'Pagi', 'Siang', 'Sore', 'Malam'],
            exactPhrases: ['halo', 'hai', 'selamat pagi', 'selamat siang', 'selamat sore', 'selamat malam', 'pagi', 'siang', 'sore', 'malam', 'hello', 'hi'],
            keywords: ['halo', 'hai', 'sapa', 'pagi', 'siang', 'sore', 'malam'],
            priorityKeywords: ['halo', 'hai'],
            negativeKeywords: ['login', 'password', 'logout', 'dashboard'],
            answer: 'Halo! Saya SILA, Asisten Informasi SILAKU. Ada yang bisa saya bantu hari ini?',
            links: [],
            suggestions: ['about_silaku', 'login_howto', 'no_account']
        },
        {
            id: 'about_silaku',
            category: 'about',
            questions: ['Apa itu SILAKU?', 'Apa fungsi website ini?', 'SILAKU digunakan untuk apa?', 'Apakah SILAKU itu?'],
            exactPhrases: ['apa itu silaku', 'apa fungsi website ini', 'silaku digunakan untuk apa', 'apa silaku'],
            keywords: ['apa', 'itu', 'silaku', 'pengertian', 'definisi', 'singkatan', 'arti'],
            priorityKeywords: ['apa itu silaku', 'apa fungsi', 'silaku adalah'],
            negativeKeywords: ['cara login', 'ganti password'],
            answer: 'SILAKU adalah Sistem Pelaporan Indikator Kinerja Utama (IKU) di Fakultas Sastra dan Ilmu Pendidikan (FSIP) Universitas Teknokrat Indonesia. Sistem ini digunakan untuk merekam, mengelola, dan melaporkan pencapaian IKU secara terintegrasi.',
            links: [{ label: 'Tentang FSIP', url: '#about' }],
            suggestions: ['silaku_purpose', 'supported_users']
        },
        {
            id: 'silaku_purpose',
            category: 'about',
            questions: ['Apa tujuan SILAKU?', 'Mengapa sistem ini dibuat?', 'Tujuan website SILAKU', 'Untuk apa dibuat SILAKU?'],
            exactPhrases: ['apa tujuan silaku', 'mengapa sistem ini dibuat', 'tujuan website silaku', 'tujuan silaku'],
            keywords: ['tujuan', 'manfaat', 'mengapa', 'dibuat', 'fungsi', 'urgensi', 'kegunaan'],
            priorityKeywords: ['tujuan silaku', 'tujuan dibuat', 'tujuan sistem'],
            negativeKeywords: ['login', 'password', 'akun'],
            answer: 'Tujuan utama SILAKU adalah mempermudah fakultas dan program studi dalam memantau, mendokumentasikan, dan mempercepat proses verifikasi data IKU guna mendukung akreditasi dan peningkatan kualitas akademis berkelanjutan.',
            links: [{ label: 'Visi & Misi', url: '#vision' }],
            suggestions: ['about_silaku', 'role_information']
        },
        {
            id: 'supported_users',
            category: 'about',
            questions: ['Siapa yang dapat menggunakan SILAKU?', 'Apakah masyarakat umum dapat masuk?', 'Siapa saja pengguna SILAKU?', 'Apakah umum bisa login?'],
            exactPhrases: ['siapa yang dapat menggunakan silaku', 'siapa saja pengguna silaku', 'apakah umum bisa login', 'apakah masyarakat umum dapat masuk'],
            keywords: ['siapa', 'pengguna', 'menggunakan', 'akses', 'masuk', 'publik', 'umum', 'masyarakat'],
            priorityKeywords: ['siapa pengguna', 'siapa yang menggunakan', 'apakah umum'],
            negativeKeywords: ['cara login', 'buat akun'],
            answer: 'SILAKU digunakan secara khusus oleh civitas akademika FSIP Universitas Teknokrat Indonesia, meliputi Admin BAAK, Pimpinan Fakultas (Dekan), Wakil Dekan, Ketua Program Studi (Kaprodi), dan Dosen. Masyarakat umum tidak dapat masuk ke sistem ini.',
            links: [],
            suggestions: ['role_information', 'no_account']
        },
        {
            id: 'login_howto',
            category: 'login',
            questions: ['Bagaimana cara login?', 'Bagaimana cara masuk ke SILAKU?', 'Di mana halaman login?', 'Cara masuk sistem'],
            exactPhrases: ['bagaimana cara login', 'bagaimana cara masuk ke silaku', 'cara login', 'cara masuk', 'halaman login', 'di mana login'],
            keywords: ['cara', 'login', 'masuk', 'halaman', 'akses', 'sistem', 'di mana', 'auth'],
            priorityKeywords: ['cara login', 'masuk ke silaku', 'halaman login', 'cara masuk'],
            negativeKeywords: ['gagal login', 'lupa password', 'akun dinonaktifkan'],
            answer: 'Untuk masuk ke SILAKU, Anda dapat mengklik tombol "Buka Halaman Login" di bawah ini. Masukkan email dan password resmi yang telah diberikan oleh pengelola sistem, lalu klik tombol "Sign In".',
            links: [{ label: 'Buka Halaman Login', url: '{{ route('login') }}' }],
            suggestions: ['login_failed', 'forgot_password', 'no_account']
        },
        {
            id: 'login_failed',
            category: 'login',
            questions: ['Mengapa saya tidak bisa login?', 'Gagal masuk sistem', 'Kenapa login gagal?', 'Tidak bisa masuk ke dashboard'],
            exactPhrases: ['mengapa saya tidak bisa login', 'gagal masuk sistem', 'kenapa login gagal', 'tidak bisa masuk'],
            keywords: ['tidak', 'bisa', 'gagal', 'login', 'masuk', 'error', 'kenapa', 'mengapa', 'ditolak'],
            priorityKeywords: ['tidak bisa login', 'gagal login', 'gagal masuk', 'kenapa login'],
            negativeKeywords: ['cara login', 'apa itu silaku'],
            answer: 'Gagal login biasanya disebabkan oleh beberapa hal: email atau password salah ketik, akun belum terdaftar, atau status akun dinonaktifkan oleh Administrator. Pastikan koneksi internet stabil dan gunakan huruf besar/kecil dengan benar pada password.',
            links: [{ label: 'Halaman Login', url: '{{ route('login') }}' }],
            suggestions: ['wrong_credentials', 'account_disabled', 'forgot_password']
        },
        {
            id: 'wrong_credentials',
            category: 'login',
            questions: ['Email atau password saya salah', 'Kredensial tidak valid', 'Salah ketik password', 'Pesan email atau password salah'],
            exactPhrases: ['email atau password saya salah', 'kredensial tidak valid', 'password salah', 'email salah'],
            keywords: ['email', 'password', 'salah', 'sandi', 'kredensial', 'invalid', 'salah ketik', 'pesan'],
            priorityKeywords: ['password salah', 'email salah', 'kredensial tidak valid'],
            negativeKeywords: ['akun dinonaktifkan', 'lupa password'],
            answer: 'Jika sistem menampilkan notifikasi bahwa email atau password salah, silakan periksa kembali ketikan Anda. Pastikan tidak ada spasi berlebih dan huruf kapital telah sesuai. Jika Anda meyakini data sudah benar namun tetap gagal, silakan hubungi pengelola untuk verifikasi.',
            links: [],
            suggestions: ['forgot_password', 'contact_admin']
        },
        {
            id: 'account_disabled',
            category: 'login',
            questions: ['Akun saya dinonaktifkan', 'Akun tidak aktif', 'Akun telah dinonaktifkan oleh administrator', 'Status akun tidak aktif'],
            exactPhrases: ['akun saya dinonaktifkan', 'akun tidak aktif', 'akun dinonaktifkan oleh administrator', 'akun dinonaktifkan'],
            keywords: ['dinonaktifkan', 'aktif', 'blokir', 'status', 'ditangguhkan', 'nonaktif', 'administrator'],
            priorityKeywords: ['akun dinonaktifkan', 'akun tidak aktif', 'akun diblokir'],
            negativeKeywords: ['cara login', 'apa itu silaku'],
            answer: 'Jika akun Anda berstatus dinonaktifkan, Anda tidak akan bisa masuk ke dashboard. Penonaktifan akun adalah kebijakan administratif (misalnya perpindahan tugas atau audit keamanan). Silakan hubungi Admin BAAK untuk mengaktifkan kembali akun Anda.',
            links: [],
            suggestions: ['contact_admin', 'login_howto']
        },
        {
            id: 'no_account',
            category: 'account',
            questions: ['Saya belum memiliki akun', 'Bagaimana mendapatkan akses?', 'Saya tidak punya akun', 'Bagaimana cara terdaftar?'],
            exactPhrases: ['saya belum memiliki akun', 'bagaimana mendapatkan akses', 'saya tidak punya akun', 'cara terdaftar'],
            keywords: ['belum', 'punya', 'memiliki', 'akun', 'akses', 'terdaftar', 'registrasi', 'daftar'],
            priorityKeywords: ['belum memiliki akun', 'tidak punya akun', 'mendapatkan akses'],
            negativeKeywords: ['cara login', 'lupa password'],
            answer: 'Sistem SILAKU tidak menyediakan menu registrasi mandiri untuk publik demi menjaga keamanan data. Akun pengguna hanya dapat dibuat dan diberikan secara resmi oleh Admin BAAK Fakultas Sastra dan Ilmu Pendidikan.',
            links: [],
            suggestions: ['account_creation', 'contact_admin']
        },
        {
            id: 'account_creation',
            category: 'account',
            questions: ['Bagaimana cara membuat akun?', 'Apakah saya bisa mendaftar sendiri?', 'Siapa yang membuat akun?', 'Prosedur pembuatan akun'],
            exactPhrases: ['bagaimana cara membuat akun', 'apakah saya bisa mendaftar sendiri', 'siapa yang membuat akun', 'cara buat akun'],
            keywords: ['buat', 'mendaftar', 'registrasi', 'pendaftaran', 'siapa', 'admin', 'baak', 'sendiri', 'prosedur'],
            priorityKeywords: ['cara membuat akun', 'bisa mendaftar sendiri', 'siapa yang membuat'],
            negativeKeywords: ['lupa password', 'dashboard'],
            answer: 'Pembuatan akun dilakukan sepenuhnya secara terpusat oleh Admin BAAK FSIP Universitas Teknokrat Indonesia. Anda dapat mengajukan permintaan akun baru kepada pihak program studi atau BAAK dengan melampirkan NIP/NIK/NITK resmi Anda.',
            links: [],
            suggestions: ['no_account', 'contact_admin']
        },
        {
            id: 'forgot_password',
            category: 'security',
            questions: ['Saya lupa password', 'Bagaimana mengganti password?', 'Lupa kata sandi', 'Reset password akun'],
            exactPhrases: ['saya lupa password', 'bagaimana mengganti password', 'lupa kata sandi', 'reset password'],
            keywords: ['lupa', 'ganti', 'reset', 'password', 'sandi', 'ubah', 'memperbarui'],
            priorityKeywords: ['lupa password', 'mengganti password', 'lupa kata sandi', 'reset password'],
            negativeKeywords: ['cara login', 'apa itu silaku'],
            answer: 'Sistem SILAKU tidak memiliki fitur reset password mandiri di halaman publik. Jika Anda lupa password atau tidak dapat mengakses akun, silakan hubungi Admin BAAK atau pengelola SILAKU melalui program studi Anda untuk mendapatkan bantuan reset password.',
            links: [],
            suggestions: ['contact_admin', 'wrong_credentials']
        },
        {
            id: 'role_information',
            category: 'role',
            questions: ['Apa saja peran pengguna?', 'Jelaskan role BAAK Kaprodi Dosen', 'Perbedaan peran di SILAKU', 'Hak akses peran'],
            exactPhrases: ['apa saja peran pengguna', 'perbedaan peran di silaku', 'role pengguna', 'hak akses peran'],
            keywords: ['peran', 'role', 'baak', 'kaprodi', 'dosen', 'pimpinan', 'dekan', 'wakil dekan', 'akses', 'perbedaan'],
            priorityKeywords: ['peran pengguna', 'role pengguna', 'perbedaan peran'],
            negativeKeywords: ['cara login', 'password salah'],
            answer: 'Terdapat 5 peran dalam SILAKU:\n1. BAAK: Super Admin dengan hak akses penuh dan persetujuan data.\n2. Kaprodi: Menginput data dan mengajukan kategori data program studi.\n3. Dosen: Menginput data pencapaian pribadi/mahasiswa.\n4. Pimpinan (Dekan) & Wakil Dekan: Hak akses baca (Read-Only) untuk grafik, peta sebaran alumni, dan ekspor laporan.',
            links: [],
            suggestions: ['about_silaku', 'supported_users']
        },
        {
            id: 'language_switch',
            category: 'general',
            questions: ['Bahasa apa saja yang didukung?', 'Bagaimana ganti bahasa?', 'Website mendukung bahasa apa?', 'Ganti bahasa inggris indonesia'],
            exactPhrases: ['bahasa apa saja yang didukung', 'bagaimana ganti bahasa', 'ganti bahasa', 'bahasa inggris indonesia'],
            keywords: ['bahasa', 'english', 'indonesia', 'ganti', 'switch', 'locale', 'terjemahan', 'dukung', 'language'],
            priorityKeywords: ['ganti bahasa', 'bahasa yang didukung', 'switch language'],
            negativeKeywords: ['cara login', 'reset password'],
            answer: 'Landing page SILAKU mendukung dua bahasa (Bilingual), yaitu Bahasa Indonesia (ID) dan Bahasa Inggris (EN). Anda dapat mengubah bahasa dengan mengklik menu pilihan bahasa (ID/EN) yang berada pada bagian kanan atas bilah navigasi.',
            links: [],
            suggestions: ['greeting', 'about_silaku']
        },
        {
            id: 'contact_admin',
            category: 'help',
            questions: ['Saya membutuhkan bantuan', 'Bagaimana menghubungi admin?', 'Siapa yang harus saya hubungi?', 'Kontak resmi bantuan'],
            exactPhrases: ['saya membutuhkan bantuan', 'bagaimana menghubungi admin', 'siapa yang harus saya hubungi', 'kontak resmi', 'hubungi admin'],
            keywords: ['bantuan', 'hubungi', 'admin', 'kontak', 'alamat', 'telpon', 'email', 'pengelola', 'nomor', 'official'],
            priorityKeywords: ['hubungi admin', 'menghubungi admin', 'membutuhkan bantuan', 'kontak resmi'],
            negativeKeywords: ['kredensial default', 'tabel database'],
            answer: 'Untuk bantuan teknis lebih lanjut, silakan hubungi Admin BAAK atau pengelola SILAKU melalui kanal resmi Fakultas Sastra dan Ilmu Pendidikan (FSIP) Universitas Teknokrat Indonesia di gedung administrasi fakultas atau email resmi fakultas.',
            links: [],
            suggestions: ['forgot_password', 'no_account']
        },
        {
            id: 'security_advice',
            category: 'security',
            questions: ['Apakah aman?', 'Bagaimana menjaga keamanan akun?', 'Tips keamanan akun', 'Bolehkah membagikan akun?'],
            exactPhrases: ['apakah aman', 'bagaimana menjaga keamanan akun', 'tips keamanan akun', 'bolehkah membagikan akun'],
            keywords: ['keamanan', 'aman', 'tips', 'jaga', 'bagikan', 'keamanan akun', 'sharing', 'sandi', 'rahasia'],
            priorityKeywords: ['keamanan akun', 'jaga keamanan', 'tips keamanan'],
            negativeKeywords: ['password admin', 'kredensial bawaan'],
            answer: 'Keamanan akun sangat penting. Jangan pernah membagikan email dan password Anda kepada siapa pun. Selalu pastikan Anda keluar (Logout) setelah menggunakan komputer bersama di lab atau perpustakaan. Gunakan password yang kuat dengan kombinasi huruf dan angka.',
            links: [],
            suggestions: ['forgot_password', 'login_howto']
        },
        {
            id: 'thanks',
            category: 'general',
            questions: ['Terima kasih', 'Makasih', 'Thank you', 'Nuhun', 'Sip', 'Oke terima kasih'],
            exactPhrases: ['terima kasih', 'makasih', 'thank you', 'nuhun', 'sip', 'oke terima kasih'],
            keywords: ['terima', 'kasih', 'makasih', 'thank', 'you', 'thanks', 'suwun', 'ok', 'oke'],
            priorityKeywords: ['terima kasih', 'makasih', 'thank you'],
            negativeKeywords: ['login', 'password'],
            answer: 'Sama-sama! Senang bisa membantu Anda. Jika ada hal lain yang ingin ditanyakan tentang SILAKU, silakan kirimkan pesan Anda.',
            links: [],
            suggestions: ['about_silaku', 'login_howto']
        },
        {
            id: 'goodbye',
            category: 'general',
            questions: ['Sampai jumpa', 'Dah', 'Bye', 'Selamat tinggal', 'Sudah dulu'],
            exactPhrases: ['sampai jumpa', 'dah', 'bye', 'selamat tinggal', 'sudah dulu'],
            keywords: ['jumpa', 'selamat', 'tinggal', 'bye', 'dah', 'dadah', 'sudah', 'cukup'],
            priorityKeywords: ['sampai jumpa', 'selamat tinggal', 'bye bye'],
            negativeKeywords: ['login', 'password'],
            answer: 'Sampai jumpa kembali! Semoga hari Anda menyenangkan. Jangan ragu untuk membuka kembali chatbot SILA jika membutuhkan bantuan.',
            links: [],
            suggestions: []
        },
        {
            id: 'unknown',
            category: 'general',
            questions: [],
            exactPhrases: [],
            keywords: [],
            priorityKeywords: [],
            negativeKeywords: [],
            answer: 'Maaf, saya belum memahami pertanyaan tersebut. Saya dapat membantu menjelaskan SILAKU, cara login, pembuatan akun, kendala password, dan cara menghubungi pengelola.',
            links: [],
            suggestions: ['about_silaku', 'login_howto', 'forgot_password', 'contact_admin']
        }
    ],
    en: [
        {
            id: 'greeting',
            category: 'general',
            questions: ['Hello', 'Hi', 'Good morning', 'Good afternoon', 'Morning', 'Afternoon', 'Evening', 'Hey'],
            exactPhrases: ['hello', 'hi', 'good morning', 'good afternoon', 'good evening', 'morning', 'afternoon', 'evening', 'hey'],
            keywords: ['hello', 'hi', 'greet', 'morning', 'afternoon', 'evening', 'hey'],
            priorityKeywords: ['hello', 'hi'],
            negativeKeywords: ['login', 'password', 'logout', 'dashboard'],
            answer: 'Hello! I am SILA, the SILAKU Information Assistant. How can I help you today?',
            links: [],
            suggestions: ['about_silaku', 'login_howto', 'no_account']
        },
        {
            id: 'about_silaku',
            category: 'about',
            questions: ['What is SILAKU?', 'What is the function of this website?', 'What is SILAKU used for?'],
            exactPhrases: ['what is silaku', 'what is the function of this website', 'what is silaku used for'],
            keywords: ['what', 'is', 'silaku', 'definition', 'meaning', 'abbreviation'],
            priorityKeywords: ['what is silaku', 'what is the function', 'silaku is'],
            negativeKeywords: ['how to login', 'change password'],
            answer: 'SILAKU is the Key Performance Indicator (IKU) Reporting System at the Faculty of Letters and Education (FSIP) Universitas Teknokrat Indonesia. This system is used to record, manage, and report IKU achievements in an integrated manner.',
            links: [{ label: 'About FSIP', url: '#about' }],
            suggestions: ['silaku_purpose', 'supported_users']
        },
        {
            id: 'silaku_purpose',
            category: 'about',
            questions: ['What is the purpose of SILAKU?', 'Why was this system created?', 'Goals of SILAKU'],
            exactPhrases: ['what is the purpose of silaku', 'why was this system created', 'goals of silaku', 'purpose of silaku'],
            keywords: ['purpose', 'goal', 'benefit', 'why', 'created', 'function', 'urgency', 'utility'],
            priorityKeywords: ['purpose of silaku', 'why was this', 'system goal'],
            negativeKeywords: ['login', 'password', 'account'],
            answer: 'The primary purpose of SILAKU is to facilitate the faculty and study programs in monitoring, documenting, and accelerating the validation of IKU data to support accreditation and continuous academic quality improvement.',
            links: [{ label: 'Vision & Mission', url: '#vision' }],
            suggestions: ['about_silaku', 'role_information']
        },
        {
            id: 'supported_users',
            category: 'about',
            questions: ['Who can use SILAKU?', 'Can the public log in?', 'Who are the users of SILAKU?', 'Can guest login?'],
            exactPhrases: ['who can use silaku', 'who are the users of silaku', 'can guest login', 'can the public log in'],
            keywords: ['who', 'user', 'use', 'access', 'log', 'public', 'guest', 'people'],
            priorityKeywords: ['who can use', 'who are the users', 'can the public'],
            negativeKeywords: ['how to login', 'create account'],
            answer: 'SILAKU is used exclusively by the academic community of FSIP Universitas Teknokrat Indonesia, including BAAK Admin, Faculty Leaders (Dean), Vice Dean, Head of Study Program (Kaprodi), and Lecturers. The general public cannot access this system.',
            links: [],
            suggestions: ['role_information', 'no_account']
        },
        {
            id: 'login_howto',
            category: 'login',
            questions: ['How do I log in?', 'How to enter SILAKU?', 'Where is the login page?', 'How to login'],
            exactPhrases: ['how do i log in', 'how to enter silaku', 'how to login', 'login page', 'where is login'],
            keywords: ['how', 'login', 'enter', 'page', 'access', 'system', 'where', 'auth'],
            priorityKeywords: ['how do i log in', 'how to login', 'login page', 'how to enter'],
            negativeKeywords: ['login failed', 'forgot password', 'account disabled'],
            answer: 'To log in to SILAKU, click the "Open Login Page" button below. Enter the official email and password credentials provided by the administrator, then click the "Sign In" button.',
            links: [{ label: 'Open Login Page', url: '{{ route('login') }}' }],
            suggestions: ['login_failed', 'forgot_password', 'no_account']
        },
        {
            id: 'login_failed',
            category: 'login',
            questions: ['Why cannot I log in?', 'Login failed', 'Why is login failing?', 'Cannot access dashboard'],
            exactPhrases: ['why cannot i log in', 'login failed', 'why is login failing', 'cannot access'],
            keywords: ['cannot', 'fail', 'failed', 'login', 'enter', 'error', 'why', 'rejected'],
            priorityKeywords: ['cannot log in', 'login failed', 'failing to login', 'cannot enter'],
            negativeKeywords: ['how to login', 'what is silaku'],
            answer: 'Login failure is usually caused by: mistyped email or password, unregistered account, or status disabled by the Administrator. Ensure your internet connection is stable and verify case sensitivity in your password.',
            links: [{ label: 'Login Page', url: '{{ route('login') }}' }],
            suggestions: ['wrong_credentials', 'account_disabled', 'forgot_password']
        },
        {
            id: 'wrong_credentials',
            category: 'login',
            questions: ['My email or password is wrong', 'Invalid credentials', 'Mistyped password'],
            exactPhrases: ['my email or password is wrong', 'invalid credentials', 'wrong password', 'wrong email'],
            keywords: ['email', 'password', 'wrong', 'credentials', 'invalid', 'mistyped', 'incorrect'],
            priorityKeywords: ['wrong password', 'wrong email', 'invalid credentials'],
            negativeKeywords: ['account disabled', 'forgot password'],
            answer: 'If the system shows an incorrect email or password notification, please recheck your spelling. Make sure there are no extra spaces and letter cases are correct. If you believe the credentials are correct but still cannot log in, contact the administrator.',
            links: [],
            suggestions: ['forgot_password', 'contact_admin']
        },
        {
            id: 'account_disabled',
            category: 'login',
            questions: ['My account is disabled', 'Inactive account', 'Account deactivated by admin'],
            exactPhrases: ['my account is disabled', 'inactive account', 'account deactivated', 'disabled account'],
            keywords: ['disabled', 'active', 'blocked', 'status', 'suspended', 'deactivated', 'administrator'],
            priorityKeywords: ['account is disabled', 'inactive account', 'blocked account'],
            negativeKeywords: ['how to login', 'what is silaku'],
            answer: 'If your account is disabled, you will not be able to log in to the dashboard. Account deactivation is an administrative policy (e.g., reassignment or security audits). Please contact the BAAK Admin to reactivate your account.',
            links: [],
            suggestions: ['contact_admin', 'login_howto']
        },
        {
            id: 'no_account',
            category: 'account',
            questions: ['I do not have an account', 'How to get access?', 'No account registered'],
            exactPhrases: ['i do not have an account', 'how to get access', 'no account', 'how to register'],
            keywords: ['no', 'have', 'account', 'access', 'registered', 'registration', 'register'],
            priorityKeywords: ['do not have an account', 'no account', 'get access'],
            negativeKeywords: ['how to login', 'forgot password'],
            answer: 'The SILAKU system does not provide self-registration for the public to maintain data security. User accounts can only be officially created and issued by the FSIP BAAK Admin.',
            links: [],
            suggestions: ['account_creation', 'contact_admin']
        },
        {
            id: 'account_creation',
            category: 'account',
            questions: ['How is an account created?', 'Can I register myself?', 'Who creates the accounts?'],
            exactPhrases: ['how is an account created', 'can i register myself', 'who creates the accounts', 'how to create account'],
            keywords: ['create', 'register', 'registration', 'who', 'admin', 'baak', 'myself', 'procedure'],
            priorityKeywords: ['how is an account created', 'can i register', 'who creates'],
            negativeKeywords: ['forgot password', 'dashboard'],
            answer: 'Account creation is fully managed centrally by the BAAK Admin of FSIP Universitas Teknokrat Indonesia. You can submit an account request through your study program or BAAK by providing your official NIP/NIK/NITK.',
            links: [],
            suggestions: ['no_account', 'contact_admin']
        },
        {
            id: 'forgot_password',
            category: 'security',
            questions: ['I forgot my password', 'How to change password?', 'Forgot passphrase', 'Reset password'],
            exactPhrases: ['i forgot my password', 'how to change password', 'forgot password', 'reset password'],
            keywords: ['forgot', 'change', 'reset', 'password', 'passphrase', 'update', 'modify'],
            priorityKeywords: ['forgot password', 'change password', 'reset password'],
            negativeKeywords: ['how to login', 'what is silaku'],
            answer: 'The SILAKU system does not have a self-service password reset feature on the public pages. If you forgot your password or cannot access your account, please contact the BAAK Admin or SILAKU managers through your study program to reset your password.',
            links: [],
            suggestions: ['contact_admin', 'wrong_credentials']
        },
        {
            id: 'role_information',
            category: 'role',
            questions: ['What are the user roles?', 'Explain BAAK Kaprodi Lecturer roles', 'Role differences in SILAKU'],
            exactPhrases: ['what are the user roles', 'role differences in silaku', 'user roles', 'role permission'],
            keywords: ['role', 'permission', 'baak', 'kaprodi', 'lecturer', 'dean', 'vice dean', 'access', 'difference'],
            priorityKeywords: ['user roles', 'role differences', 'permission roles'],
            negativeKeywords: ['how to login', 'wrong password'],
            answer: 'There are 5 roles in SILAKU:\n1. BAAK: Super Admin with full access and data approval permissions.\n2. Kaprodi: Inputs data and proposes study program data categories.\n3. Dosen (Lecturer): Inputs personal/student achievement data.\n4. Pimpinan (Dean) & Wakil Dekan: Read-Only access to charts, alumni map, and reports export.',
            links: [],
            suggestions: ['about_silaku', 'supported_users']
        },
        {
            id: 'language_switch',
            category: 'general',
            questions: ['What languages are supported?', 'How to change language?', 'Does the website support English?'],
            exactPhrases: ['what languages are supported', 'how to change language', 'change language', 'support english'],
            keywords: ['language', 'english', 'indonesia', 'change', 'switch', 'locale', 'translation', 'support'],
            priorityKeywords: ['change language', 'languages supported', 'switch language'],
            negativeKeywords: ['how to login', 'reset password'],
            answer: 'The SILAKU landing page supports two languages (Bilingual): Indonesian (ID) and English (EN). You can change the active language by clicking the language options (ID/EN) located at the top-right corner of the navigation bar.',
            links: [],
            suggestions: ['greeting', 'about_silaku']
        },
        {
            id: 'contact_admin',
            category: 'help',
            questions: ['I need help', 'How to contact the admin?', 'Who should I contact?', 'Official contact support'],
            exactPhrases: ['i need help', 'how to contact the admin', 'who should i contact', 'official contact', 'contact admin'],
            keywords: ['help', 'contact', 'admin', 'support', 'address', 'phone', 'email', 'manager', 'number', 'official'],
            priorityKeywords: ['contact admin', 'need help', 'official contact', 'contact the admin'],
            negativeKeywords: ['default credentials', 'database table'],
            answer: 'For further technical assistance, please contact the BAAK Admin or SILAKU managers through the official channels of the Faculty of Letters and Education (FSIP) Universitas Teknokrat Indonesia at the faculty administrative office or official email.',
            links: [],
            suggestions: ['forgot_password', 'no_account']
        },
        {
            id: 'security_advice',
            category: 'security',
            questions: ['Is it safe?', 'How to keep account secure?', 'Account security tips'],
            exactPhrases: ['is it safe', 'how to keep account secure', 'security tips', 'can i share my account'],
            keywords: ['security', 'safe', 'tips', 'keep', 'share', 'sharing', 'password', 'secret'],
            priorityKeywords: ['account security', 'keep secure', 'security tips'],
            negativeKeywords: ['admin password', 'default credentials'],
            answer: 'Account security is crucial. Never share your email and password credentials with anyone. Always make sure to Log Out after using shared computers in laboratories or libraries. Use a strong password containing a combination of letters and numbers.',
            links: [],
            suggestions: ['forgot_password', 'login_howto']
        },
        {
            id: 'thanks',
            category: 'general',
            questions: ['Thank you', 'Thanks', 'OK thanks', 'Appreciate it'],
            exactPhrases: ['thank you', 'thanks', 'ok thanks', 'appreciate it'],
            keywords: ['thank', 'thanks', 'you', 'ok', 'okay'],
            priorityKeywords: ['thank you', 'thanks'],
            negativeKeywords: ['login', 'password'],
            answer: 'You are welcome! Glad I could help. If you have any other questions about SILAKU, feel free to send your message.',
            links: [],
            suggestions: ['about_silaku', 'login_howto']
        },
        {
            id: 'goodbye',
            category: 'general',
            questions: ['Goodbye', 'Bye', 'See you later', 'Talk to you later'],
            exactPhrases: ['goodbye', 'bye', 'see you later', 'talk to you later'],
            keywords: ['goodbye', 'bye', 'see', 'you', 'later', 'quit'],
            priorityKeywords: ['goodbye', 'bye bye', 'see you'],
            negativeKeywords: ['login', 'password'],
            answer: 'Goodbye! Hope you have a wonderful day. Feel free to open the SILA chatbot again if you need any assistance.',
            links: [],
            suggestions: []
        },
        {
            id: 'unknown',
            category: 'general',
            questions: [],
            exactPhrases: [],
            keywords: [],
            priorityKeywords: [],
            negativeKeywords: [],
            answer: 'Sorry, I could not understand that question. I can help with information about SILAKU, login access, account creation, password issues, and contacting the administrator.',
            links: [],
            suggestions: ['about_silaku', 'login_howto', 'forgot_password', 'contact_admin']
        }
    ]
};
</script>
