@props(['isDashboard' => false])

<script>
window.SILAKU_FAQ_DATA = {
    id: {!! json_encode($isDashboard ? [
        [
            'id' => 'greeting',
            'category' => 'general',
            'questions' => ['Halo', 'Hai', 'Selamat pagi', 'Selamat siang', 'Pagi', 'Siang', 'Sore', 'Malam'],
            'exactPhrases' => ['halo', 'hai', 'selamat pagi', 'selamat siang', 'selamat sore', 'selamat malam', 'pagi', 'siang', 'sore', 'malam', 'hello', 'hi'],
            'keywords' => ['halo', 'hai', 'sapa', 'pagi', 'siang', 'sore', 'malam'],
            'priorityKeywords' => ['halo', 'hai'],
            'negativeKeywords' => ['input', 'approval', 'ekspor'],
            'answer' => 'Halo! Saya SILA. Sebagai pengguna terautentikasi di dashboard SILAKU, saya siap membantu memandu Anda mengenai cara input data, alur persetujuan BAAK, ekspor laporan, dan manajemen kategori data. Apa yang ingin Anda tanyakan?',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'input_dosen_mahasiswa', 'input_alumni', 'export_data_howto', 'create_category_howto']
        ],
        [
            'id' => 'data_approval_workflow',
            'category' => 'approval',
            'questions' => ['Bagaimana alur persetujuan data?', 'Bagaimana sistem approval data?', 'Alur persetujuan BAAK', 'Approval data'],
            'exactPhrases' => ['bagaimana alur persetujuan data', 'bagaimana sistem approval data', 'alur persetujuan baak', 'approval data', 'alur persetujuan', 'sistem approval'],
            'keywords' => ['alur', 'persetujuan', 'data', 'approval', 'baak', 'menyetujui', 'tolak', 'status', 'pending'],
            'priorityKeywords' => ['alur persetujuan', 'sistem approval', 'persetujuan baak'],
            'negativeKeywords' => ['ekspor', 'excel', 'pdf'],
            'answer' => 'Dalam SILAKU, role Kaprodi dan Dosen dapat menginput data (Dosen, Mahasiswa, Alumni) secara mandiri tanpa memerlukan persetujuan BAAK. Namun, jika role Kaprodi/Dosen ingin menghapus data, tindakan tersebut memerlukan persetujuan dari BAAK terlebih dahulu. Khusus untuk Kaprodi, pembuatan kategori data baru juga memerlukan persetujuan dari BAAK sebelum aktif.',
            'links' => [],
            'suggestions' => ['input_dosen_mahasiswa', 'input_alumni', 'baak_approval_howto']
        ],
        [
            'id' => 'input_dosen_mahasiswa',
            'category' => 'input',
            'questions' => ['Bagaimana cara menginput data Dosen atau Mahasiswa?', 'Cara input dosen', 'Cara tambah mahasiswa', 'Cara isi data kategori'],
            'exactPhrases' => ['bagaimana cara menginput data dosen atau mahasiswa', 'cara input dosen', 'cara tambah mahasiswa', 'cara isi data kategori', 'input dosen', 'input mahasiswa'],
            'keywords' => ['cara', 'input', 'dosen', 'mahasiswa', 'tambah', 'data', 'kategori', 'isi', 'formulir'],
            'priorityKeywords' => ['input dosen', 'input mahasiswa', 'tambah data dosen', 'tambah data mahasiswa'],
            'negativeKeywords' => ['alumni', 'ekspor'],
            'answer' => 'Untuk menginput data pada kategori Dosen atau Mahasiswa, masuk ke menu "Kategori Data" di sidebar kiri. Pilih kategori data yang ingin Anda isi, kemudian klik tombol "Tambah Data" di bagian atas tabel. Isi formulir sesuai kolom yang ditentukan, lalu klik Simpan. Data baru akan langsung tersimpan.',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'create_category_howto', 'export_data_howto']
        ],
        [
            'id' => 'input_alumni',
            'category' => 'input',
            'questions' => ['Bagaimana cara menginput data Alumni?', 'Cara input alumni', 'Tambah data alumni', 'Formulir alumni'],
            'exactPhrases' => ['bagaimana cara menginput data alumni', 'cara input alumni', 'tambah data alumni', 'formulir alumni', 'input alumni'],
            'keywords' => ['cara', 'input', 'alumni', 'tambah', 'data', 'formulir', 'lokasi', 'kerja', 'geocoding', 'alamat'],
            'priorityKeywords' => ['input alumni', 'tambah data alumni', 'cara input alumni'],
            'negativeKeywords' => ['dosen', 'mahasiswa'],
            'answer' => 'Untuk menginput data Alumni, klik menu "Data Alumni" di sidebar kiri, kemudian tekan tombol "Tambah Alumni". Masukkan informasi alumni, seperti Nama, Instansi, Posisi, beserta Lokasi Kerja. Untuk Lokasi Kerja, mulailah mengetik untuk melihat saran wilayah otomatis yang disediakan sistem (didukung auto-complete alamat). Setelah selesai, simpan data tersebut.',
            'links' => [],
            'suggestions' => ['alumni_map_info', 'export_data_howto']
        ],
        [
            'id' => 'alumni_map_info',
            'category' => 'map',
            'questions' => ['Di mana saya bisa melihat peta sebaran geografis alumni?', 'Peta sebaran alumni', 'Peta sebaran alumni bekerja', 'Lokasi peta alumni'],
            'exactPhrases' => ['di mana saya bisa melihat peta sebaran geografis alumni', 'peta sebaran alumni', 'peta sebaran alumni bekerja', 'lokasi peta alumni', 'peta alumni'],
            'keywords' => ['peta', 'sebaran', 'geografis', 'alumni', 'bekerja', 'lokasi', 'map', 'leaflet'],
            'priorityKeywords' => ['peta sebaran', 'sebaran alumni', 'peta alumni'],
            'negativeKeywords' => ['input', 'tambah', 'excel'],
            'answer' => 'Peta sebaran geografis alumni bekerja telah dipindahkan ke halaman khusus. Anda dapat mengaksesnya dengan mengklik menu "Peta Sebaran Alumni" pada sidebar kiri. Di halaman tersebut, Anda dapat memfilter tampilan peta berdasarkan Lampung, Indonesia, atau seluruh Dunia.',
            'links' => [['label' => 'Buka Peta Sebaran', 'url' => route('dashboard.map')]],
            'suggestions' => ['input_alumni', 'export_data_howto']
        ],
        [
            'id' => 'export_data_howto',
            'category' => 'export',
            'questions' => ['Bagaimana cara mengekspor data ke Excel atau PDF?', 'Cara download laporan', 'Ekspor excel pdf', 'Download data'],
            'exactPhrases' => ['bagaimana cara mengekspor data ke excel atau pdf', 'cara download laporan', 'ekspor excel pdf', 'download data', 'ekspor excel', 'ekspor pdf'],
            'keywords' => ['ekspor', 'export', 'excel', 'pdf', 'download', 'unduh', 'laporan', 'cetak'],
            'priorityKeywords' => ['ekspor excel', 'ekspor pdf', 'download laporan', 'ekspor data'],
            'negativeKeywords' => ['input', 'tambah'],
            'answer' => 'Anda dapat mengunduh data dalam format Excel maupun PDF. Pada halaman detail kategori (Dosen/Mahasiswa) atau di halaman daftar Alumni, terdapat tombol "Ekspor Excel" dan "Ekspor PDF" di atas tabel data. Klik tombol tersebut untuk mengunduh laporan secara instan.',
            'links' => [],
            'suggestions' => ['input_dosen_mahasiswa', 'input_alumni']
        ],
        [
            'id' => 'create_category_howto',
            'category' => 'category',
            'questions' => ['Bagaimana cara menambah kategori baru?', 'Cara buat kategori', 'Tambah kategori dosen mahasiswa', 'Pengajuan kategori baru'],
            'exactPhrases' => ['bagaimana cara menambah kategori baru', 'cara buat kategori', 'tambah kategori', 'pengajuan kategori', 'kategori baru'],
            'keywords' => ['kategori', 'baru', 'tambah', 'buat', 'kolom', 'fields', 'kaprodi', 'baak', 'pengajuan'],
            'priorityKeywords' => ['tambah kategori', 'buat kategori', 'kategori baru', 'pengajuan kategori'],
            'negativeKeywords' => ['alumni', 'ekspor'],
            'answer' => 'Hanya role Kaprodi dan BAAK yang dapat mengelola kategori data. Kaprodi dapat menekan menu "Kategori Data" di sidebar, lalu klik "Tambah Kategori". Tentukan nama kategori, ikon, dan definisikan kolom-kolom (fields) beserta tipe datanya. Setelah disimpan, status kategori akan berada dalam antrean (pending) untuk ditinjau dan disetujui oleh BAAK.',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'baak_approval_howto']
        ],
        [
            'id' => 'baak_approval_howto',
            'category' => 'approval',
            'questions' => ['Bagaimana cara BAAK menyetujui data?', 'Cara approval BAAK', 'Menu persetujuan BAAK', 'Menolak pengajuan data'],
            'exactPhrases' => ['bagaimana cara baak menyetujui data', 'cara approval baak', 'persetujuan baak', 'menyetujui data', 'menolak pengajuan'],
            'keywords' => ['baak', 'menyetujui', 'tolak', 'approval', 'persetujuan', 'approvals', 'massal', 'bulk'],
            'priorityKeywords' => ['approval baak', 'menyetujui data', 'persetujuan baak'],
            'negativeKeywords' => ['dosen', 'alumni'],
            'answer' => 'Sebagai BAAK, Anda dapat mengakses menu "Persetujuan (Approvals)" di sidebar kiri. Menu ini menampilkan daftar pengajuan kategori baru dan daftar permintaan penghapusan data. Anda dapat menyetujui atau menolak pengajuan satu per satu, atau menggunakan fitur persetujuan massal (bulk approval) dengan mencentang beberapa data sekaligus.',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'activity_log_info']
        ],
        [
            'id' => 'activity_log_info',
            'category' => 'logs',
            'questions' => ['Siapa yang bisa melihat Log Aktivitas?', 'Fungsi log aktifitas', 'Melihat riwayat input data'],
            'exactPhrases' => ['siapa yang bisa melihat log aktivitas', 'fungsi log aktivitas', 'melihat riwayat', 'log aktivitas', 'log aktifitas'],
            'keywords' => ['log', 'aktivitas', 'aktifitas', 'riwayat', 'audit', 'pimpinan', 'dekan', 'baak'],
            'priorityKeywords' => ['log aktivitas', 'log aktifitas', 'riwayat input'],
            'negativeKeywords' => ['input data', 'excel'],
            'answer' => 'Menu "Log Aktivitas" di sidebar kiri merekam seluruh riwayat aktivitas penambahan, pengeditan, dan penghapusan data oleh Dosen dan Kaprodi. Menu ini hanya dapat diakses oleh role BAAK, Pimpinan/Dekan, dan Wakil Dekan untuk keperluan pemantauan dan audit tata kelola data.',
            'links' => [],
            'suggestions' => ['baak_approval_howto']
        ],
        [
            'id' => 'thanks',
            'category' => 'general',
            'questions' => ['Terima kasih', 'Makasih', 'Oke terima kasih', 'Sip thanks'],
            'exactPhrases' => ['terima kasih', 'makasih', 'oke terima kasih', 'thanks', 'suwun'],
            'keywords' => ['terima', 'kasih', 'makasih', 'oke', 'thanks'],
            'priorityKeywords' => ['terima kasih', 'makasih'],
            'negativeKeywords' => ['input', 'approval'],
            'answer' => 'Sama-sama! Senang bisa membantu Anda memandu sistem SILAKU. Jika ada hal teknis lain yang ingin ditanyakan, silakan kirimkan pesan Anda.',
            'links' => [],
            'suggestions' => ['input_dosen_mahasiswa', 'input_alumni']
        ],
        [
            'id' => 'goodbye',
            'category' => 'general',
            'questions' => ['Sampai jumpa', 'Dah', 'Bye', 'Selamat tinggal', 'Sudah dulu'],
            'exactPhrases' => ['sampai jumpa', 'dah', 'bye', 'selamat tinggal', 'sudah dulu'],
            'keywords' => ['jumpa', 'selamat', 'tinggal', 'bye', 'dah', 'dadah', 'sudah', 'cukup'],
            'priorityKeywords' => ['sampai jumpa', 'selamat tinggal', 'bye bye'],
            'negativeKeywords' => ['input', 'approval'],
            'answer' => 'Sampai jumpa kembali! Selamat melanjutkan aktivitas Anda di dashboard SILAKU.',
            'links' => [],
            'suggestions' => []
        ],
        [
            'id' => 'unknown',
            'category' => 'general',
            'questions' => [],
            'exactPhrases' => [],
            'keywords' => [],
            'priorityKeywords' => [],
            'negativeKeywords' => [],
            'answer' => 'Maaf, saya belum memahami pertanyaan tersebut. Di dalam dashboard ini, saya dapat memandu Anda tentang cara input Dosen/Mahasiswa/Alumni, ekspor Excel/PDF, alur persetujuan BAAK, pengajuan kategori baru, dan menu log aktivitas.',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'input_dosen_mahasiswa', 'input_alumni', 'export_data_howto']
        ]
    ] : [
        [
            'id' => 'greeting',
            'category' => 'general',
            'questions' => ['Halo', 'Hai', 'Selamat pagi', 'Selamat siang', 'Pagi', 'Siang', 'Sore', 'Malam'],
            'exactPhrases' => ['halo', 'hai', 'selamat pagi', 'selamat siang', 'selamat sore', 'selamat malam', 'pagi', 'siang', 'sore', 'malam', 'hello', 'hi'],
            'keywords' => ['halo', 'hai', 'sapa', 'pagi', 'siang', 'sore', 'malam'],
            'priorityKeywords' => ['halo', 'hai'],
            'negativeKeywords' => ['login', 'password', 'logout', 'dashboard'],
            'answer' => 'Halo! Saya SILA, Asisten Informasi SILAKU. Ada yang bisa saya bantu hari ini?',
            'links' => [],
            'suggestions' => ['about_silaku', 'login_howto', 'no_account']
        ],
        [
            'id' => 'about_silaku',
            'category' => 'about',
            'questions' => ['Apa itu SILAKU?', 'Apa fungsi website ini?', 'SILAKU digunakan untuk apa?', 'Apakah SILAKU itu?'],
            'exactPhrases' => ['apa itu silaku', 'apa fungsi website ini', 'silaku digunakan untuk apa', 'apa silaku'],
            'keywords' => ['apa', 'itu', 'silaku', 'pengertian', 'definisi', 'singkatan', 'arti'],
            'priorityKeywords' => ['apa itu silaku', 'apa fungsi', 'silaku adalah'],
            'negativeKeywords' => ['cara login', 'ganti password'],
            'answer' => 'SILAKU adalah Sistem Pelaporan Indikator Kinerja Utama (IKU) di Fakultas Sastra dan Ilmu Pendidikan (FSIP) Universitas Teknokrat Indonesia. Sistem ini digunakan untuk merekam, mengelola, dan melaporkan pencapaian IKU secara terintegrasi.',
            'links' => [['label' => 'Tentang FSIP', 'url' => '#about']],
            'suggestions' => ['silaku_purpose', 'supported_users']
        ],
        [
            'id' => 'silaku_purpose',
            'category' => 'about',
            'questions' => ['Apa tujuan SILAKU?', 'Mengapa sistem ini dibuat?', 'Tujuan website SILAKU', 'Untuk apa dibuat SILAKU?'],
            'exactPhrases' => ['apa tujuan silaku', 'mengapa sistem ini dibuat', 'tujuan website silaku', 'tujuan silaku'],
            'keywords' => ['tujuan', 'manfaat', 'mengapa', 'dibuat', 'fungsi', 'urgensi', 'kegunaan'],
            'priorityKeywords' => ['tujuan silaku', 'tujuan dibuat', 'tujuan sistem'],
            'negativeKeywords' => ['login', 'password', 'akun'],
            'answer' => 'Tujuan utama SILAKU adalah mempermudah fakultas dan program studi dalam memantau, mendokumentasikan, dan mempercepat proses verifikasi data IKU guna mendukung akreditasi dan peningkatan kualitas akademis berkelanjutan.',
            'links' => [['label' => 'Visi & Misi', 'url' => '#vision']],
            'suggestions' => ['about_silaku', 'role_information']
        ],
        [
            'id' => 'supported_users',
            'category' => 'about',
            'questions' => ['Siapa yang dapat menggunakan SILAKU?', 'Apakah masyarakat umum dapat masuk?', 'Siapa saja pengguna SILAKU?', 'Apakah umum bisa login?'],
            'exactPhrases' => ['siapa yang dapat menggunakan silaku', 'siapa saja pengguna silaku', 'apakah umum bisa login', 'apakah masyarakat umum dapat masuk'],
            'keywords' => ['siapa', 'pengguna', 'menggunakan', 'akses', 'masuk', 'publik', 'umum', 'masyarakat'],
            'priorityKeywords' => ['siapa pengguna', 'siapa yang menggunakan', 'apakah umum'],
            'negativeKeywords' => ['cara login', 'buat akun'],
            'answer' => 'SILAKU digunakan secara khusus oleh civitas akademika FSIP Universitas Teknokrat Indonesia, meliputi Admin BAAK, Pimpinan Fakultas (Dekan), Wakil Dekan, Ketua Program Studi (Kaprodi), dan Dosen. Masyarakat umum tidak dapat masuk ke sistem ini.',
            'links' => [],
            'suggestions' => ['role_information', 'no_account']
        ],
        [
            'id' => 'login_howto',
            'category' => 'login',
            'questions' => ['Bagaimana cara login?', 'Bagaimana cara masuk ke SILAKU?', 'Di mana halaman login?', 'Cara masuk sistem'],
            'exactPhrases' => ['bagaimana cara login', 'bagaimana cara masuk ke silaku', 'cara login', 'cara masuk', 'halaman login', 'di mana login'],
            'keywords' => ['cara', 'login', 'masuk', 'halaman', 'akses', 'sistem', 'di mana', 'auth'],
            'priorityKeywords' => ['cara login', 'masuk ke silaku', 'halaman login', 'cara masuk'],
            'negativeKeywords' => ['login failed', 'forgot password', 'account disabled'],
            'answer' => 'Untuk masuk ke SILAKU, Anda dapat mengklik tombol "Buka Halaman Login" di bawah ini. Masukkan email dan password resmi yang telah diberikan oleh pengelola sistem, lalu klik tombol "Sign In".',
            'links' => [['label' => 'Buka Halaman Login', 'url' => route('login')]],
            'suggestions' => ['login_failed', 'forgot_password', 'no_account']
        ],
        [
            'id' => 'login_failed',
            'category' => 'login',
            'questions' => ['Mengapa saya tidak bisa login?', 'Gagal masuk sistem', 'Kenapa login gagal?', 'Tidak bisa masuk ke dashboard'],
            'exactPhrases' => ['mengapa saya tidak bisa login', 'gagal masuk sistem', 'kenapa login gagal', 'tidak bisa masuk'],
            'keywords' => ['tidak', 'bisa', 'gagal', 'login', 'masuk', 'error', 'kenapa', 'mengapa', 'ditolak'],
            'priorityKeywords' => ['tidak bisa login', 'gagal login', 'gagal masuk', 'kenapa login'],
            'negativeKeywords' => ['cara login', 'apa itu silaku'],
            'answer' => 'Gagal login biasanya disebabkan oleh beberapa hal: email atau password salah ketik, akun belum terdaftar, atau status akun dinonaktifkan oleh Administrator. Pastikan koneksi internet stabil dan gunakan huruf besar/kecil dengan benar pada password.',
            'links' => [['label' => 'Halaman Login', 'url' => route('login')]],
            'suggestions' => ['wrong_credentials', 'account_disabled', 'forgot_password']
        ],
        [
            'id' => 'wrong_credentials',
            'category' => 'login',
            'questions' => ['Email atau password saya salah', 'Kredensial tidak valid', 'Salah ketik password', 'Pesan email atau password salah'],
            'exactPhrases' => ['email atau password saya salah', 'kredensial tidak valid', 'password salah', 'email salah'],
            'keywords' => ['email', 'password', 'salah', 'sandi', 'kredensial', 'invalid', 'salah ketik', 'pesan'],
            'priorityKeywords' => ['password salah', 'email salah', 'kredensial tidak valid'],
            'negativeKeywords' => ['akun dinonaktifkan', 'lupa password'],
            'answer' => 'Jika sistem menampilkan notifikasi bahwa email atau password salah, silakan periksa kembali ketikan Anda. Pastikan tidak ada spasi berlebih dan huruf kapital telah sesuai. Jika Anda meyakini data sudah benar namun tetap gagal, silakan hubungi pengelola untuk verifikasi.',
            'links' => [],
            'suggestions' => ['forgot_password', 'contact_admin']
        ],
        [
            'id' => 'account_disabled',
            'category' => 'login',
            'questions' => ['Akun saya dinonaktifkan', 'Akun tidak aktif', 'Akun telah dinonaktifkan oleh administrator', 'Status akun tidak aktif'],
            'exactPhrases' => ['akun saya dinonaktifkan', 'akun tidak aktif', 'akun dinonaktifkan oleh administrator', 'akun dinonaktifkan'],
            'keywords' => ['dinonaktifkan', 'aktif', 'blokir', 'status', 'ditangguhkan', 'nonaktif', 'administrator'],
            'priorityKeywords' => ['akun dinonaktifkan', 'akun tidak aktif', 'akun diblokir'],
            'negativeKeywords' => ['cara login', 'apa itu silaku'],
            'answer' => 'Jika akun Anda berstatus dinonaktifkan, Anda tidak akan bisa masuk ke dashboard. Penonaktifan akun adalah kebijakan administratif (misalnya perpindahan tugas atau audit keamanan). Silakan hubungi Admin BAAK untuk mengaktifkan kembali akun Anda.',
            'links' => [],
            'suggestions' => ['contact_admin', 'login_howto']
        ],
        [
            'id' => 'no_account',
            'category' => 'account',
            'questions' => ['Saya tidak punya akun', 'Bagaimana cara mendapatkan akses?', 'Akun tidak terdaftar'],
            'exactPhrases' => ['saya tidak punya akun', 'bagaimana cara mendapatkan akses', 'tidak punya akun', 'cara mendaftar'],
            'keywords' => ['tidak', 'punya', 'akun', 'akses', 'terdaftar', 'pendaftaran', 'daftar'],
            'priorityKeywords' => ['tidak punya akun', 'akses akun', 'cara mendaftar'],
            'negativeKeywords' => ['cara login', 'lupa password'],
            'answer' => 'Sistem SILAKU tidak menyediakan pendaftaran mandiri secara terbuka bagi publik untuk menjaga keamanan data. Akun pengguna hanya dapat dibuat dan diberikan secara resmi oleh Admin BAAK FSIP.',
            'links' => [],
            'suggestions' => ['account_creation', 'contact_admin']
        ],
        [
            'id' => 'account_creation',
            'category' => 'account',
            'questions' => ['Bagaimana akun dibuat?', 'Apakah saya bisa daftar sendiri?', 'Siapa yang membuat akun?'],
            'exactPhrases' => ['bagaimana akun dibuat', 'apakah saya bisa daftar sendiri', 'siapa yang membuat akun', 'cara membuat akun'],
            'keywords' => ['buat', 'mendaftar', 'pendaftaran', 'siapa', 'admin', 'baak', 'sendiri', 'prosedur'],
            'priorityKeywords' => ['bagaimana akun dibuat', 'daftar sendiri', 'siapa membuat'],
            'negativeKeywords' => ['lupa password', 'dashboard'],
            'answer' => 'Pembuatan akun dikelola sepenuhnya secara terpusat oleh Admin BAAK FSIP Universitas Teknokrat Indonesia. Anda dapat mengajukan permohonan akun melalui program studi atau BAAK dengan melampirkan NIP/NIK/NITK resmi Anda.',
            'links' => [],
            'suggestions' => ['no_account', 'contact_admin']
        ],
        [
            'id' => 'forgot_password',
            'category' => 'security',
            'questions' => ['Saya lupa password', 'Bagaimana cara ganti password?', 'Lupa kata sandi', 'Reset kata sandi'],
            'exactPhrases' => ['saya lupa password', 'bagaimana cara ganti password', 'lupa password', 'reset password'],
            'keywords' => ['lupa', 'ganti', 'reset', 'password', 'sandi', 'ubah', 'perbarui'],
            'priorityKeywords' => ['lupa password', 'ganti password', 'reset password'],
            'negativeKeywords' => ['cara login', 'apa itu silaku'],
            'answer' => 'Sistem SILAKU tidak memiliki fitur reset password mandiri pada halaman publik. Jika Anda lupa password atau tidak bisa mengakses akun, silakan hubungi Admin BAAK atau pengelola SILAKU melalui program studi Anda untuk mereset password.',
            'links' => [],
            'suggestions' => ['contact_admin', 'wrong_credentials']
        ],
        [
            'id' => 'role_information',
            'category' => 'role',
            'questions' => ['Apa saja role pengguna?', 'Jelaskan role BAAK Kaprodi Dosen', 'Perbedaan hak akses SILAKU'],
            'exactPhrases' => ['apa saja role pengguna', 'perbedaan hak akses silaku', 'role pengguna', 'hak akses role'],
            'keywords' => ['role', 'hak', 'akses', 'baak', 'kaprodi', 'dosen', 'dekan', 'wadek', 'perbedaan'],
            'priorityKeywords' => ['role pengguna', 'perbedaan hak', 'hak akses'],
            'negativeKeywords' => ['cara login', 'password salah'],
            'answer' => 'Terdapat 5 role di SILAKU:\n1. BAAK: Super Admin dengan akses penuh & persetujuan data.\n2. Kaprodi: Mengisi data & mengajukan kategori data prodi.\n3. Dosen: Mengisi data dosen/mahasiswa/alumni prodi sendiri.\n4. Pimpinan (Dekan) & Wakil Dekan: Akses Read-Only untuk grafik, peta, dan ekspor laporan.',
            'links' => [],
            'suggestions' => ['about_silaku', 'supported_users']
        ],
        [
            'id' => 'language_switch',
            'category' => 'general',
            'questions' => ['Bahasa apa saja yang didukung?', 'Cara mengubah bahasa', 'Apakah ada pilihan bahasa inggris?'],
            'exactPhrases' => ['bahasa apa saja yang didukung', 'cara mengubah bahasa', 'ubah bahasa', 'bahasa inggris'],
            'keywords' => ['bahasa', 'inggris', 'indonesia', 'ubah', 'ganti', 'locale', 'terjemahan', 'dukung'],
            'priorityKeywords' => ['ubah bahasa', 'bahasa didukung', 'ganti bahasa'],
            'negativeKeywords' => ['cara login', 'reset password'],
            'answer' => 'Landing page SILAKU mendukung dua bahasa (Bilingual), yaitu Bahasa Indonesia (ID) dan Bahasa Inggris (EN). Anda dapat mengubah bahasa dengan mengklik opsi bahasa (ID/EN) yang terletak di pojok kanan atas navigation bar.',
            'links' => [],
            'suggestions' => ['greeting', 'about_silaku']
        ],
        [
            'id' => 'contact_admin',
            'category' => 'help',
            'questions' => ['Saya butuh bantuan', 'Bagaimana menghubungi admin?', 'Siapa yang harus saya hubungi?', 'Kontak resmi support'],
            'exactPhrases' => ['saya butuh bantuan', 'bagaimana menghubungi admin', 'siapa yang harus hubungi', 'kontak resmi', 'hubungi admin'],
            'keywords' => ['bantuan', 'hubungi', 'admin', 'support', 'alamat', 'telepon', 'email', 'pengelola', 'nomor', 'resmi'],
            'priorityKeywords' => ['hubungi admin', 'butuh bantuan', 'kontak resmi', 'menghubungi admin'],
            'negativeKeywords' => ['kredensial bawaan', 'tabel database'],
            'answer' => 'Untuk bantuan teknis lebih lanjut, silakan hubungi Admin BAAK atau pengelola SILAKU melalui saluran resmi Fakultas Sastra dan Ilmu Pendidikan (FSIP) Universitas Teknokrat Indonesia di ruang sekretariat fakultas atau email resmi.',
            'links' => [],
            'suggestions' => ['forgot_password', 'no_account']
        ],
        [
            'id' => 'security_advice',
            'category' => 'security',
            'questions' => ['Apakah aman?', 'Cara menjaga keamanan akun', 'Tips keamanan akun'],
            'exactPhrases' => ['apakah aman', 'cara menjaga keamanan akun', 'tips keamanan', 'apakah boleh bagi akun'],
            'keywords' => ['keamanan', 'aman', 'tips', 'menjaga', 'bagi', 'bagikan', 'password', 'rahasia'],
            'priorityKeywords' => ['keamanan akun', 'menjaga keamanan', 'tips keamanan'],
            'negativeKeywords' => ['password dekan', 'password aminudin'],
            'answer' => 'Keamanan akun sangat penting. Jangan pernah membagikan email dan password Anda kepada siapapun. Pastikan selalu melakukan Log Out setelah menggunakan komputer bersama di laboratorium atau perpustakaan. Gunakan password yang kuat dengan kombinasi huruf dan angka.',
            'links' => [],
            'suggestions' => ['forgot_password', 'login_howto']
        ],
        [
            'id' => 'thanks',
            'category' => 'general',
            'questions' => ['Terima kasih', 'Makasih', 'Oke terima kasih', 'Sip thanks'],
            'exactPhrases' => ['terima kasih', 'makasih', 'oke terima kasih', 'thanks', 'suwun'],
            'keywords' => ['terima', 'kasih', 'makasih', 'oke', 'thanks'],
            'priorityKeywords' => ['terima kasih', 'makasih'],
            'negativeKeywords' => ['login', 'password'],
            'answer' => 'Sama-sama! Senang bisa membantu Anda. Jika ada pertanyaan lain tentang SILAKU, silakan kirimkan pesan Anda.',
            'links' => [],
            'suggestions' => ['about_silaku', 'login_howto']
        ],
        [
            'id' => 'goodbye',
            'category' => 'general',
            'questions' => ['Sampai jumpa', 'Dah', 'Bye', 'Selamat tinggal', 'Sudah dulu'],
            'exactPhrases' => ['sampai jumpa', 'dah', 'bye', 'selamat tinggal', 'sudah dulu'],
            'keywords' => ['jumpa', 'selamat', 'tinggal', 'bye', 'dah', 'dadah', 'sudah', 'cukup'],
            'priorityKeywords' => ['sampai jumpa', 'selamat tinggal', 'bye bye'],
            'negativeKeywords' => ['login', 'password'],
            'answer' => 'Sampai jumpa kembali! Semoga hari Anda menyenangkan. Jangan ragu untuk membuka kembali chatbot SILA jika membutuhkan bantuan.',
            'links' => [],
            'suggestions' => []
        ],
        [
            'id' => 'unknown',
            'category' => 'general',
            'questions' => [],
            'exactPhrases' => [],
            'keywords' => [],
            'priorityKeywords' => [],
            'negativeKeywords' => [],
            'answer' => 'Maaf, saya belum memahami pertanyaan tersebut. Saya dapat membantu menjelaskan SILAKU, cara login, pembuatan akun, kendala password, dan cara menghubungi pengelola.',
            'links' => [],
            'suggestions' => ['about_silaku', 'login_howto', 'forgot_password', 'contact_admin']
        ]
    ]) !!},
    en: {!! json_encode($isDashboard ? [
        [
            'id' => 'greeting',
            'category' => 'general',
            'questions' => ['Hello', 'Hi', 'Good morning', 'Good afternoon', 'Morning', 'Afternoon', 'Evening', 'Hey'],
            'exactPhrases' => ['hello', 'hi', 'good morning', 'good afternoon', 'good evening', 'morning', 'afternoon', 'evening', 'hey'],
            'keywords' => ['hello', 'hi', 'greet', 'morning', 'afternoon', 'evening', 'hey'],
            'priorityKeywords' => ['hello', 'hi'],
            'negativeKeywords' => ['input', 'approval', 'export'],
            'answer' => 'Hello! I am SILA. As an authenticated user on the SILAKU dashboard, I am ready to guide you on data input, BAAK approval workflows, exporting reports, and managing data categories. What would you like to ask?',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'input_dosen_mahasiswa', 'input_alumni', 'export_data_howto', 'create_category_howto']
        ],
        [
            'id' => 'data_approval_workflow',
            'category' => 'approval',
            'questions' => ['How does the data approval workflow work?', 'How to get data approved?', 'BAAK approval system', 'Data approval'],
            'exactPhrases' => ['how does the data approval workflow work', 'how to get data approved', 'baak approval system', 'data approval', 'approval process', 'approval workflow'],
            'keywords' => ['workflow', 'approval', 'data', 'baak', 'approve', 'reject', 'status', 'pending'],
            'priorityKeywords' => ['approval workflow', 'approval system', 'baak approval'],
            'negativeKeywords' => ['export', 'excel', 'pdf'],
            'answer' => 'In SILAKU, Kaprodi and Dosen roles can input data (Dosen, Mahasiswa, Alumni) directly without BAAK approval. However, if they want to delete data, it requires prior BAAK approval. Specifically for Kaprodi, creating a new data category also requires BAAK approval before it becomes active.',
            'links' => [],
            'suggestions' => ['input_dosen_mahasiswa', 'input_alumni', 'baak_approval_howto']
        ],
        [
            'id' => 'input_dosen_mahasiswa',
            'category' => 'input',
            'questions' => ['How do I input Lecturer or Student data?', 'How to input lecturer', 'How to add student', 'Input category data'],
            'exactPhrases' => ['how do i input lecturer or student data', 'how to input lecturer', 'how to add student', 'input category data', 'input lecturer', 'input student'],
            'keywords' => ['how', 'input', 'lecturer', 'student', 'add', 'data', 'category', 'fill', 'form'],
            'priorityKeywords' => ['input lecturer', 'input student', 'add lecturer data', 'add student data'],
            'negativeKeywords' => ['alumni', 'export'],
            'answer' => 'To input data in the Dosen or Mahasiswa categories, go to the "Kategori Data" menu on the left sidebar. Select the category you want to populate, then click the "Tambah Data" button at the top of the table. Fill out the form and click Save. The new data will be stored immediately.',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'create_category_howto', 'export_data_howto']
        ],
        [
            'id' => 'input_alumni',
            'category' => 'input',
            'questions' => ['How do I input Alumni data?', 'How to input alumni', 'Add alumni data', 'Alumni form'],
            'exactPhrases' => ['how do i input alumni data', 'how to input alumni', 'add alumni data', 'alumni form', 'input alumni'],
            'keywords' => ['how', 'input', 'alumni', 'add', 'data', 'form', 'location', 'work', 'geocoding', 'address'],
            'priorityKeywords' => ['input alumni', 'add alumni data', 'how to input alumni'],
            'negativeKeywords' => ['lecturer', 'student'],
            'answer' => 'To input Alumni data, click the "Data Alumni" menu on the left sidebar, then click the "Tambah Alumni" button. Enter the alumni\'s information, including Name, Institution, Position, and Work Location. For the Work Location, start typing to see automatic region suggestions (supported by address auto-complete). Save when finished.',
            'links' => [],
            'suggestions' => ['alumni_map_info', 'export_data_howto']
        ],
        [
            'id' => 'alumni_map_info',
            'category' => 'map',
            'questions' => ['Where can I see the alumni geographical distribution map?', 'Alumni sebaran map', 'Alumni geographical map', 'Where is alumni map'],
            'exactPhrases' => ['where can i see the alumni geographical distribution map', 'alumni sebaran map', 'alumni geographical map', 'where is alumni map', 'alumni map'],
            'keywords' => ['map', 'geographical', 'distribution', 'alumni', 'location', 'sebaran', 'leaflet'],
            'priorityKeywords' => ['geographical map', 'alumni map', 'distribution map'],
            'negativeKeywords' => ['input', 'add', 'excel'],
            'answer' => 'The alumni geographical distribution map has been moved to a dedicated page. You can access it by clicking the "Peta Sebaran Alumni" menu on the left sidebar. On that page, you can filter locations by Lampung, Indonesia, or World.',
            'links' => [['label' => 'Open Sebaran Map', 'url' => route('dashboard.map')]],
            'suggestions' => ['input_alumni', 'export_data_howto']
        ],
        [
            'id' => 'export_data_howto',
            'category' => 'export',
            'questions' => ['How do I export data to Excel or PDF?', 'How to download reports', 'Export excel pdf', 'Download data'],
            'exactPhrases' => ['how do i export data to excel or pdf', 'how to download reports', 'export excel pdf', 'download data', 'export excel', 'export pdf'],
            'keywords' => ['export', 'excel', 'pdf', 'download', 'report', 'print'],
            'priorityKeywords' => ['export excel', 'export pdf', 'download reports', 'export data'],
            'negativeKeywords' => ['input', 'add'],
            'answer' => 'You can download reports in Excel or PDF formats. On the category detail page (Dosen/Mahasiswa) or on the Alumni list page, click the "Ekspor Excel" or "Ekspor PDF" buttons located above the data table to download instantly.',
            'links' => [],
            'suggestions' => ['input_dosen_mahasiswa', 'input_alumni']
        ],
        [
            'id' => 'create_category_howto',
            'category' => 'category',
            'questions' => ['How do I add a new category?', 'How to create category', 'Add lecturer student category', 'New category request'],
            'exactPhrases' => ['how do i add a new category', 'how to create category', 'add category', 'propose category', 'new category'],
            'keywords' => ['category', 'new', 'add', 'create', 'columns', 'fields', 'kaprodi', 'baak', 'request'],
            'priorityKeywords' => ['add category', 'create category', 'new category', 'category request'],
            'negativeKeywords' => ['alumni', 'export'],
            'answer' => 'Only Kaprodi and BAAK roles can manage data categories. A Kaprodi can go to the "Kategori Data" menu, click "Tambah Kategori", define the name, icon, and the fields with their data types. Once saved, it will be pending BAAK review and approval.',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'baak_approval_howto']
        ],
        [
            'id' => 'baak_approval_howto',
            'category' => 'approval',
            'questions' => ['How does BAAK approve requests?', 'BAAK approval process', 'Where is approval page', 'Rejecting requests'],
            'exactPhrases' => ['how does baak approve requests', 'baak approval process', 'approval page', 'rejecting requests', 'baak approval'],
            'keywords' => ['baak', 'approve', 'reject', 'approval', 'approvals', 'bulk', 'massal'],
            'priorityKeywords' => ['baak approval', 'approve requests', 'approvals page'],
            'negativeKeywords' => ['lecturer', 'alumni'],
            'answer' => 'As a BAAK user, you can access the "Persetujuan (Approvals)" menu on the left sidebar. This menu displays new category proposals and deletion requests. You can approve or reject them individually, or perform bulk actions by checking multiple items at once.',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'activity_log_info']
        ],
        [
            'id' => 'activity_log_info',
            'category' => 'logs',
            'questions' => ['Who can view Activity Logs?', 'Activity log purpose', 'Check data history'],
            'exactPhrases' => ['who can view activity logs', 'activity log purpose', 'check data history', 'activity log', 'activity logs'],
            'keywords' => ['log', 'activity', 'logs', 'history', 'audit', 'dean', 'vice dean', 'baak'],
            'priorityKeywords' => ['activity logs', 'activity log', 'data history'],
            'negativeKeywords' => ['input data', 'excel'],
            'answer' => 'The "Log Aktivitas" menu on the left sidebar logs all creation, editing, and deletion operations done by Lecturers and Kaprodi. This log is readable only by BAAK, Pimpinan/Dean, and Wakil Dekan for monitoring and audit purposes.',
            'links' => [],
            'suggestions' => ['baak_approval_howto']
        ],
        [
            'id' => 'thanks',
            'category' => 'general',
            'questions' => ['Thank you', 'Thanks', 'OK thanks', 'Appreciate it'],
            'exactPhrases' => ['thank you', 'thanks', 'ok thanks', 'appreciate it'],
            'keywords' => ['thank', 'thanks', 'you', 'ok', 'okay'],
            'priorityKeywords' => ['thank you', 'thanks'],
            'negativeKeywords' => ['input', 'approval'],
            'answer' => 'You are welcome! Glad I could help you navigate the SILAKU dashboard. If you have other technical questions, feel free to send your message.',
            'links' => [],
            'suggestions' => ['input_dosen_mahasiswa', 'input_alumni']
        ],
        [
            'id' => 'goodbye',
            'category' => 'general',
            'questions' => ['Goodbye', 'Bye', 'See you later', 'Talk to you later'],
            'exactPhrases' => ['goodbye', 'bye', 'see you later', 'talk to you later'],
            'keywords' => ['goodbye', 'bye', 'see', 'you', 'later', 'quit'],
            'priorityKeywords' => ['goodbye', 'bye bye', 'see you'],
            'negativeKeywords' => ['input', 'approval'],
            'answer' => 'Goodbye! Have a great day and enjoy working with the SILAKU dashboard.',
            'links' => [],
            'suggestions' => []
        ],
        [
            'id' => 'unknown',
            'category' => 'general',
            'questions' => [],
            'exactPhrases' => [],
            'keywords' => [],
            'priorityKeywords' => [],
            'negativeKeywords' => [],
            'answer' => 'Sorry, I could not understand that question. In this dashboard, I can guide you on inputting Lecturers/Students/Alumni, exporting Excel/PDF, BAAK approvals, category creation requests, and activity logs.',
            'links' => [],
            'suggestions' => ['data_approval_workflow', 'input_dosen_mahasiswa', 'input_alumni', 'export_data_howto']
        ]
    ] : [
        [
            'id' => 'greeting',
            'category' => 'general',
            'questions' => ['Hello', 'Hi', 'Good morning', 'Good afternoon', 'Morning', 'Afternoon', 'Evening', 'Hey'],
            'exactPhrases' => ['hello', 'hi', 'good morning', 'good afternoon', 'good evening', 'morning', 'afternoon', 'evening', 'hey'],
            'keywords' => ['hello', 'hi', 'greet', 'morning', 'afternoon', 'evening', 'hey'],
            'priorityKeywords' => ['hello', 'hi'],
            'negativeKeywords' => ['login', 'password', 'logout', 'dashboard'],
            'answer' => 'Hello! I am SILA, the SILAKU Information Assistant. How can I help you today?',
            'links' => [],
            'suggestions' => ['about_silaku', 'login_howto', 'no_account']
        ],
        [
            'id' => 'about_silaku',
            'category' => 'about',
            'questions' => ['What is SILAKU?', 'What is the function of this website?', 'What is SILAKU used for?'],
            'exactPhrases' => ['what is silaku', 'what is the function of this website', 'what is silaku used for'],
            'keywords' => ['what', 'is', 'silaku', 'definition', 'meaning', 'abbreviation'],
            'priorityKeywords' => ['what is silaku', 'what is the function', 'silaku is'],
            'negativeKeywords' => ['how to login', 'change password'],
            'answer' => 'SILAKU is the Key Performance Indicator (IKU) Reporting System at the Faculty of Letters and Education (FSIP) Universitas Teknokrat Indonesia. This system is used to record, manage, and report IKU achievements in an integrated manner.',
            'links' => [['label' => 'About FSIP', 'url' => '#about']],
            'suggestions' => ['silaku_purpose', 'supported_users']
        ],
        [
            'id' => 'silaku_purpose',
            'category' => 'about',
            'questions' => ['What is the purpose of SILAKU?', 'Why was this system created?', 'Goals of SILAKU'],
            'exactPhrases' => ['what is the purpose of silaku', 'why was this system created', 'goals of silaku', 'purpose of silaku'],
            'keywords' => ['purpose', 'goal', 'benefit', 'why', 'created', 'function', 'urgency', 'utility'],
            'priorityKeywords' => ['purpose of silaku', 'why was this', 'system goal'],
            'negativeKeywords' => ['login', 'password', 'account'],
            'answer' => 'The primary purpose of SILAKU is to facilitate the faculty and study programs in monitoring, documenting, and accelerating the validation of IKU data to support accreditation and continuous academic quality improvement.',
            'links' => [['label' => 'Vision & Mission', 'url' => '#vision']],
            'suggestions' => ['about_silaku', 'role_information']
        ],
        [
            'id' => 'supported_users',
            'category' => 'about',
            'questions' => ['Who can use SILAKU?', 'Can the public log in?', 'Who are the users of SILAKU?', 'Can guest login?'],
            'exactPhrases' => ['who can use silaku', 'who are the users of silaku', 'can guest login', 'can the public log in'],
            'keywords' => ['who', 'user', 'use', 'access', 'log', 'public', 'guest', 'people'],
            'priorityKeywords' => ['who can use', 'who are the users', 'can the public'],
            'negativeKeywords' => ['how to login', 'create account'],
            'answer' => 'SILAKU is used exclusively by the academic community of FSIP Universitas Teknokrat Indonesia, including BAAK Admin, Faculty Leaders (Dean), Vice Dean, Head of Study Program (Kaprodi), and Lecturers. The general public cannot access this system.',
            'links' => [],
            'suggestions' => ['role_information', 'no_account']
        ],
        [
            'id' => 'login_howto',
            'category' => 'login',
            'questions' => ['How do I log in?', 'How to enter SILAKU?', 'Where is the login page?', 'How to login'],
            'exactPhrases' => ['how do i log in', 'how to enter silaku', 'how to login', 'login page', 'where is login'],
            'keywords' => ['how', 'login', 'enter', 'page', 'access', 'system', 'where', 'auth'],
            'priorityKeywords' => ['how do i log in', 'how to login', 'login page', 'how to enter'],
            'negativeKeywords' => ['login failed', 'forgot password', 'account disabled'],
            'answer' => 'To log in to SILAKU, click the "Open Login Page" button below. Enter the official email and password credentials provided by the administrator, then click the "Sign In" button.',
            'links' => [['label' => 'Open Login Page', 'url' => route('login')]],
            'suggestions' => ['login_failed', 'forgot_password', 'no_account']
        ],
        [
            'id' => 'login_failed',
            'category' => 'login',
            'questions' => ['Why cannot I log in?', 'Login failed', 'Why is login failing?', 'Cannot access dashboard'],
            'exactPhrases' => ['why cannot i log in', 'login failed', 'why is login failing', 'cannot access'],
            'keywords' => ['cannot', 'fail', 'failed', 'login', 'enter', 'error', 'why', 'rejected'],
            'priorityKeywords' => ['cannot log in', 'login failed', 'failing to login', 'cannot enter'],
            'negativeKeywords' => ['how to login', 'what is silaku'],
            'answer' => 'Login failure is usually caused by: mistyped email or password, unregistered account, or status disabled by the Administrator. Ensure your internet connection is stable and verify case sensitivity in your password.',
            'links' => [['label' => 'Login Page', 'url' => route('login')]],
            'suggestions' => ['wrong_credentials', 'account_disabled', 'forgot_password']
        ],
        [
            'id' => 'wrong_credentials',
            'category' => 'login',
            'questions' => ['My email or password is wrong', 'Invalid credentials', 'Mistyped password'],
            'exactPhrases' => ['my email or password is wrong', 'invalid credentials', 'wrong password', 'wrong email'],
            'keywords' => ['email', 'password', 'wrong', 'credentials', 'invalid', 'mistyped', 'incorrect'],
            'priorityKeywords' => ['wrong password', 'wrong email', 'invalid credentials'],
            'negativeKeywords' => ['account disabled', 'forgot password'],
            'answer' => 'If the system shows an incorrect email or password notification, please recheck your spelling. Make sure there are no extra spaces and letter cases are correct. If you believe the credentials are correct but still cannot log in, contact the administrator.',
            'links' => [],
            'suggestions' => ['forgot_password', 'contact_admin']
        ],
        [
            'id' => 'account_disabled',
            'category' => 'login',
            'questions' => ['My account is disabled', 'Inactive account', 'Account deactivated by admin'],
            'exactPhrases' => ['my account is disabled', 'inactive account', 'account deactivated', 'disabled account'],
            'keywords' => ['disabled', 'active', 'blocked', 'status', 'suspended', 'deactivated', 'administrator'],
            'priorityKeywords' => ['account is disabled', 'inactive account', 'blocked account'],
            'negativeKeywords' => ['how to login', 'what is silaku'],
            'answer' => 'If your account is disabled, you will not be able to log in to the dashboard. Account deactivation is an administrative policy (e.g., reassignment or security audits). Please contact the BAAK Admin to reactivate your account.',
            'links' => [],
            'suggestions' => ['contact_admin', 'login_howto']
        ],
        [
            'id' => 'no_account',
            'category' => 'account',
            'questions' => ['I do not have an account', 'How to get access?', 'No account registered'],
            'exactPhrases' => ['i do not have an account', 'how to get access', 'no account', 'how to register'],
            'keywords' => ['no', 'have', 'account', 'access', 'registered', 'registration', 'register'],
            'priorityKeywords' => ['do not have an account', 'no account', 'get access'],
            'negativeKeywords' => ['how to login', 'forgot password'],
            'answer' => 'The SILAKU system does not provide self-registration for the public to maintain data security. User accounts can only be officially created and issued by the FSIP BAAK Admin.',
            'links' => [],
            'suggestions' => ['account_creation', 'contact_admin']
        ],
        [
            'id' => 'account_creation',
            'category' => 'account',
            'questions' => ['How is an account created?', 'Can I register myself?', 'Who creates the accounts?'],
            'exactPhrases' => ['how is an account created', 'can i register myself', 'who creates the accounts', 'how to create account'],
            'keywords' => ['create', 'register', 'registration', 'who', 'admin', 'baak', 'myself', 'procedure'],
            'priorityKeywords' => ['how is an account created', 'can i register', 'who creates'],
            'negativeKeywords' => ['forgot password', 'dashboard'],
            'answer' => 'Account creation is fully managed centrally by the BAAK Admin of FSIP Universitas Teknokrat Indonesia. You can submit an account request through your study program or BAAK by providing your official NIP/NIK/NITK.',
            'links' => [],
            'suggestions' => ['no_account', 'contact_admin']
        ],
        [
            'id' => 'forgot_password',
            'category' => 'security',
            'questions' => ['I forgot my password', 'How to change password?', 'Forgot passphrase', 'Reset password'],
            'exactPhrases' => ['i forgot my password', 'how to change password', 'forgot password', 'reset password'],
            'keywords' => ['forgot', 'change', 'reset', 'password', 'passphrase', 'update', 'modify'],
            'priorityKeywords' => ['forgot password', 'change password', 'reset password'],
            'negativeKeywords' => ['how to login', 'what is silaku'],
            'answer' => 'The SILAKU system does not have a self-service password reset feature on the public pages. If you forgot your password or cannot access your account, please contact the BAAK Admin or SILAKU managers through your study program to reset your password.',
            'links' => [],
            'suggestions' => ['contact_admin', 'wrong_credentials']
        ],
        [
            'id' => 'role_information',
            'category' => 'role',
            'questions' => ['What are the user roles?', 'Explain BAAK Kaprodi Lecturer roles', 'Role differences in SILAKU'],
            'exactPhrases' => ['what are the user roles', 'role differences in silaku', 'user roles', 'role permission'],
            'keywords' => ['role', 'permission', 'baak', 'kaprodi', 'lecturer', 'dean', 'vice dean', 'access', 'difference'],
            'priorityKeywords' => ['user roles', 'role differences', 'permission roles'],
            'negativeKeywords' => ['how to login', 'wrong password'],
            'answer' => 'There are 5 roles in SILAKU:\n1. BAAK: Super Admin with full access and data approval permissions.\n2. Kaprodi: Inputs data and proposes study program data categories.\n3. Dosen (Lecturer): Inputs personal/student achievement data.\n4. Pimpinan (Dean) & Wakil Dekan: Read-Only access to charts, alumni map, and reports export.',
            'links' => [],
            'suggestions' => ['about_silaku', 'supported_users']
        ],
        [
            'id' => 'language_switch',
            'category' => 'general',
            'questions' => ['What languages are supported?', 'How to change language?', 'Does the website support English?'],
            'exactPhrases' => ['what languages are supported', 'how to change language', 'change language', 'support english'],
            'keywords' => ['language', 'english', 'indonesia', 'change', 'switch', 'locale', 'translation', 'support'],
            'priorityKeywords' => ['change language', 'languages supported', 'switch language'],
            'negativeKeywords' => ['how to login', 'reset password'],
            'answer' => 'The SILAKU landing page supports two languages (Bilingual): Indonesian (ID) and English (EN). You can change the active language by clicking the language options (ID/EN) located at the top-right corner of the navigation bar.',
            'links' => [],
            'suggestions' => ['greeting', 'about_silaku']
        ],
        [
            'id' => 'contact_admin',
            'category' => 'help',
            'questions' => ['I need help', 'How to contact the admin?', 'Who should I contact?', 'Official contact support'],
            'exactPhrases' => ['i need help', 'how to contact the admin', 'who should i contact', 'official contact', 'contact admin'],
            'keywords' => ['help', 'contact', 'admin', 'support', 'address', 'phone', 'email', 'manager', 'number', 'official'],
            'priorityKeywords' => ['contact admin', 'need help', 'official contact', 'contact the admin'],
            'negativeKeywords' => ['default credentials', 'database table'],
            'answer' => 'For further technical assistance, please contact the BAAK Admin or SILAKU managers through the official channels of the Faculty of Letters and Education (FSIP) Universitas Teknokrat Indonesia at the faculty administrative office or official email.',
            'links' => [],
            'suggestions' => ['forgot_password', 'no_account']
        ],
        [
            'id' => 'security_advice',
            'category' => 'security',
            'questions' => ['Is it safe?', 'How to keep account secure?', 'Account security tips'],
            'exactPhrases' => ['is it safe', 'how to keep account secure', 'security tips', 'can i share my account'],
            'keywords' => ['security', 'safe', 'tips', 'keep', 'share', 'sharing', 'password', 'secret'],
            'priorityKeywords' => ['account security', 'keep secure', 'security tips'],
            'negativeKeywords' => ['admin password', 'default credentials'],
            'answer' => 'Account security is crucial. Never share your email and password credentials with anyone. Always make sure to Log Out after using shared computers in laboratories or libraries. Use a strong password containing a combination of letters and numbers.',
            'links' => [],
            'suggestions' => ['forgot_password', 'login_howto']
        ],
        [
            'id' => 'thanks',
            'category' => 'general',
            'questions' => ['Thank you', 'Thanks', 'OK thanks', 'Appreciate it'],
            'exactPhrases' => ['thank you', 'thanks', 'ok thanks', 'appreciate it'],
            'keywords' => ['thank', 'thanks', 'you', 'ok', 'okay'],
            'priorityKeywords' => ['thank you', 'thanks'],
            'negativeKeywords' => ['login', 'password'],
            'answer' => 'You are welcome! Glad I could help. If you have any other questions about SILAKU, feel free to send your message.',
            'links' => [],
            'suggestions' => ['about_silaku', 'login_howto']
        ],
        [
            'id' => 'goodbye',
            'category' => 'general',
            'questions' => ['Goodbye', 'Bye', 'See you later', 'Talk to you later'],
            'exactPhrases' => ['goodbye', 'bye', 'see you later', 'talk to you later'],
            'keywords' => ['goodbye', 'bye', 'see', 'you', 'later', 'quit'],
            'priorityKeywords' => ['goodbye', 'bye bye', 'see you'],
            'negativeKeywords' => ['login', 'password'],
            'answer' => 'Goodbye! Hope you have a wonderful day. Feel free to open the SILA chatbot again if you need any assistance.',
            'links' => [],
            'suggestions' => []
        ],
        [
            'id' => 'unknown',
            'category' => 'general',
            'questions' => [],
            'exactPhrases' => [],
            'keywords' => [],
            'priorityKeywords' => [],
            'negativeKeywords' => [],
            'answer' => 'Sorry, I could not understand that question. I can help with information about SILAKU, login access, account creation, password issues, and contacting the administrator.',
            'links' => [],
            'suggestions' => ['about_silaku', 'login_howto', 'forgot_password', 'contact_admin']
        ]
    ]) !!}
};
</script>
